### ISSUE TITLE
Atom: APM syntax error

### ISSUE THREAD

**Issue by andyrichardson** [FZUG/repo#106]
Issue (believed to be with boom package) prevents apm from running.

``` /usr/lib/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
```

Could be an issue with the official fedora repo as I get the following error when installing atom 

```
error: unpacking of archive failed on file /usr/lib/node_modules/boom/node_modules/hoek: cpio: rename
```

Installing boom and hoek via npm does not resolve issue.

```
npm install -g boom hoek
```

To my knowledge, the use of _const_ has been supported since nodejs 4+ so this issue would imply an outdated version of node however I am running _v5.11.1._ and _nodejs-atom-package-manager-1.10.0-2.git87b4bcb.fc23.x86_64_

**Comment by 1dot75cm** [comment]
I use `node` (0.10.42.fc23) of offical fedora repo to build apm package (`nodejs-atom-package-manager` rpm, `apm` need `node 0.10.42` to work). If you use `node` (5.11.0) of nodesource repo, then you need to use the new version of the `node` to rebuild all of the `npm` package.

```
$ sudo dnf install libgnome-keyring-devel
$ cp -r /usr/lib/node_modules/atom-package-manager ~/
$ cd ~/atom-package-manager
$ npm install
$ npm install -g --prefix build/usr
$ sudo rm -rf /usr/lib/node_modules/atom-package-manager/
$ sudo cp -r build/usr/lib/node_modules/atom-package-manager /usr/lib/node_modules/
$ apm -v
```

Another way, I think I need to copy apm depends to `/usr/lib/node_modules/atom-package-manager/node_modules/`. It can give priority to use the old version of the package, instead of `/usr/lib/node_modules/` directory under the new version of the package. However, which the package affect the normal operation of apm? @andyrichardson

**Comment by andyrichardson** [comment]
Based on the [_hoek_ package.json](https://github.com/hapijs/hoek/blob/master/package.json), hoek requires a node version of _>= 4.0.0_. 

You say you are using a version which _hoek_ does not support as the use of _const_ within strict mode in node is not supported in versions prior to _v4.0.0._ 

I'm unsure how this translates to my issue as I am running a supported node version (although the syntax error specified in my initial issue post implies otherwise). Is the repo forcing apm to use a pre _v4_ version of node?

I can confirm that this was not an issue in the previous commit to the repo and is not an issue when installing using the atom provided _rpm_.

**Comment by 1dot75cm** [comment]
Well, I use node 4.4.4 to build apm. It looks like work fine. Please test [nodejs-atom-package-manager-1.10.0-3.git87b4bcb.fc23.x86_64](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/316032/).

Thanks report. @andyrichardson
