### ISSUE TITLE
VSCode version should be ugpraded to 1.3.0

### ISSUE THREAD

**Issue by sudoforge** [FZUG/repo#140]
1.3.0 was released, rpm is still at 1.2.x

**Comment by 1dot75cm** [comment]
The package is building on Copr [384155](https://copr.fedorainfracloud.org/coprs/mosquito/vscode/build/384155/), please test later. @bddenhartog

**Comment by sudoforge** [comment]
@1dot75cm Looks like there's an issue finishing GCs:

https://copr-be.cloud.fedoraproject.org/results/mosquito/vscode/fedora-24-i386/00384155-vscode/build.log.gz

**Comment by 1dot75cm** [comment]
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

It's looks like not enough memory (GC fail?). Perhaps node's option may be fix it (`node --v8-options`).  If I use the `node 0.12`, the GC is working properly. But vscode required `node 5`, otherwise fail to build. @bddenhartog 

The `--max-old-space-size` v8 options not working (`node --max_old_space_size=1024 /bin/npm`). I'm not good idea for this.
