### ISSUE TITLE
Package request: OneDrive

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#180]
https://github.com/skilion/onedrive

I've not tested and also not verify it's license. I'll do it later

**Comment by ghost** [comment]
It seems released under [GPLv3](https://github.com/skilion/onedrive/blob/master/LICENSE). :+1: 

Not sure if this app does work.

**Comment by sztsian** [comment]
Do you know how hard it is to compile this? ☹ This app is written in D Lang. Makefile uses dmd as compiler however [dmd](https://github.com/dlang/dmd) is not totally open source solution (althouth its code is open there) while the open source replacement for dmd do not work.
Reference https://github.com/skilion/onedrive/issues/105

**Comment by ghost** [comment]
Why have to use open source replacement of DMD? I haven't found licence details about D language and DMD. However, D Language Foundation open sourced their source code and allow other people free to use. It means it is possible and okay to utilize official DMD for compilation.

BTW, if everything fully open sourced and well licensed, I suppose this package could go to Fedora official repository instead of FZUG.

**Comment by sztsian** [comment]
Say, the problem lies like, we utilize CI or Fedora Copr. So if I want to build this, I need to make the makefile or SPEC run under Fedora environments. However, DMD is not in Fedora, and it do not have clear copyright saying allow to redistribute or not, thus DMD is hart to be utilized in Copr. Then I need to find alternatives. ldmd2 and ldc2 are in Fedora but they failed to build this app.

**Comment by sztsian** [comment]
While I can not build it so I can not test it. I'll make this as a help wanted in lable.

**Comment by ghost** [comment]
You don't need to redistribute DMD actually. Simply grab it from [dlang website](http://dlang.org/download.html#dmd) and install rpm version or compile from source. Then, you are ready to compile onedrive and redistribute onedrive package. According to Fedora Copr limitation, I recommend doing this locally for test; and communicating with @1dot75cm (Adding DMD package in local repository of CI for building only. NOT redistribute DMD package) in order to allow FZUG build and redistribute onedrive package.

<br>

> we utilize CI or Fedora Copr

Utilizing DMD to compile onedrive in CI is quite simple. You can download whatever version you want from [dlang website](http://dlang.org/download.html#dmd). If you want to utilize it in Fedora Copr, I am afraid that you need to manually build dmd package based on source code from [dlang/dmd](https://github.com/dlang/dmd) for build dependency. I suppose it should be allowed in Fedora Copr.

> DMD is not in Fedora

You can download whatever version you want from [dlang website](http://dlang.org/download.html#dmd), including rpm package for Fedora and CentOS.

> it do not have clear copyright saying allow to redistribute or not

I haven't found any copyright declaration either. I suppose it is free to redistribute because the repository is stored in GitHub public repository; and I assume this software is released without any licence because there is not copyright declaration in [dlang website download section](http://dlang.org/download.html#dmd).

**Comment by ghost** [comment]
I checked [Gentoo wiki](https://wiki.gentoo.org/wiki/Dlang). It points:

> Speaking of which, is open source, but not free software due to being part of the old commercial C++ compiler. In particular DMD is not to be redistributed.

It means utilizing a script (in building onedrive package) to download DMD from dlang website or compile manually is okay. But DMD cannot be packaged and redistributed (from third party instead of official website).

BTW, have you tried GDC or LDC? There are [three compilers](http://wiki.dlang.org/Compilers) for dlang.

**Comment by sztsian** [comment]
> BTW, have you tried GDC or LDC? There are three compilers for dlang.

I've tried LDC as I mentioned earlier. No lucky. 
GDC is not in Fedora. I remember I need to compile it as well (but I do not have time to do it last night). So basically it is the status

**Comment by ghost** [comment]
Well, then I think using formal DMD should be the simplest. There is no licence problem as long as you download it from official dlang website.

**Comment by sztsian** [comment]
I will try gdc first. And if gdc not work, then dmd. As you may see, I'm much careful on license and legal related affairs.

**Comment by abraunegg** [comment]
Have a look here for SPEC files that I use

https://github.com/abraunegg/onedrive/tree/master/spec

**Comment by sztsian** [comment]
@abraunegg  Great, thanks.
However what I concern is the legal (or redistribution) restriction of DMD, I will look carefully into it's license first (clearly it is copyrighted and not fully licensed in Open Source licenses)

**Comment by abraunegg** [comment]
You only need DMD to compile onedrive - the resulting binary has no external dependencies on DMD or files. On MyNAS Storage Appliance (www.mynas.com.au) I dont include DMD - just the onedrive client.

Hope that helps

**Comment by sztsian** [comment]
@abraunegg Thanks for making it clear. However I did some dirty hack to the code and now it compiles with ldc2. I will send pull request soon after it is fully tested.
