### ISSUE TITLE
fedora26无法使用该源

### ISSUE THREAD

**Issue by dianbanjiu** [FZUG/repo#255]
更新到fedora26后，下载软件时显示：“
同步仓库 'fzug-free' 缓存失败，禁用。
同步仓库 'fzug-nonfree' 缓存失败，禁用。
”
该如何解决？？

**Comment by alick** [comment]
因为这个软件源尚未支持新发布的 F26，我们需要一些时日将各种软件在 F26 上构建出来，抱歉。

请暂时禁用 fzug-free 和 fzug-nonfree 软件源，一段时间后如果支持了再启用。

Regards,
Alick

**Comment by shaojing1779** [comment]
f26源什么时候发布？

**Comment by chinaluopiao** [comment]
你把repo里面的$server开头的那个字符串替换成25就可以用了

**Comment by wayss000** [comment]
The same problem.

**Comment by ivancheng458** [comment]
这样修改成25的源后，会不会更新26的下一代的系统呢？
f26源什么时候发布？

**Comment by alick** [comment]
我不建议字符串替换冲成25，这样有的软件可以用有的不能，很难保证。

**Comment by ivancheng458** [comment]
哦，多谢哈2017年8月3日 上午5:21，Alick Zhao <notifications@github.com>写道：我不建议字符串替换冲成25，这样有的软件可以用有的不能，很难保证。

**Comment by dengbangjie** [comment]
要不咱们F27再见？

**Comment by shensl** [comment]
在目前这个情况下只能将$releasever更改成25啊，毕竟是新装的26

**Comment by jinke159** [comment]
@alick 能否把进度告知一下感谢

**Comment by alick** [comment]
@jinke159 我不知道，抱歉

@1dot75cm @sztsian please help answer. Also I'd like to help make progess on this issue

**Comment by sztsian** [comment]
Hi,
中文用户组repo目前有211个spec文件，截至昨晚我们已经能够成功编译其中的110个。由于CI不能正常工作，当前暂时需要维护者手工修复和打包，恐怕还需要一些时间。请谅解。

**Comment by carter1980** [comment]
咨询一下，FZUG Repo发布Fedora26版本有没有具体的时间点呀？

**Comment by sztsian** [comment]
> 咨询一下，FZUG Repo发布Fedora26版本有没有具体的时间点呀？

很抱歉，我们无法拿出明确的时间点。我们会尽快将能成功编译的包推送到源。

**Comment by alick** [comment]
Hi @sztsian ,

We'd better put those 110 packages in f26 repo, available to end users. Rather than waiting for all to build successfully.

We'd better have a status tracking page (temporary, no need to be pretty), so others who wanna help know what to be working on.

**Comment by sztsian** [comment]
Hi @alick ,

@1dot75cm is now working on publishing the built packages. The server need some checks so it would take some time (hopefully not too much), and also need to separate the packages that might be conflicts with Fedora/rpmfusion since I did not take that into consideration when building the packages.

For packages that failed, logs are uploaded in my Fedora people page
https://zsun.fedorapeople.org/pub/fzug/logs/
For these logs, please don't touch the ones starting with rpmfusion (RPMFusion for F26 is already available) as well as deepin_project (We are pushing Deepin related packages into Fedora targeting Fedora 28. So the spec file might work for Rawhide but no longer for Fedora 26)

**Comment by sztsian** [comment]
All,
Now all available packages that can be built for Fedora 26 goes live. Please try and report separate issues for those who has problems.

大家好。现在所有在 Fedora 26 上编译成功的包已经推送。如有包存在依赖或者安装问题，请开独立的issue。

https://repo.fdzh.org/FZUG/free/26/x86_64/

**Comment by alick** [comment]
confirmed as usable

**Comment by ghost** [comment]
有没有终极方法解决这个问题,Fedora27同样会遇到这个问题

**Comment by sztsian** [comment]
@Hikhackerlyn
issue中所述问题已经被修好了。
如果你看到的是
``` 同步仓库 'fzug-nonfree' 缓存失败，禁用。```
那么这是预期的，因为现在fzug-nofree全部编译失败了。

**Comment by haixuxu** [comment]
netease 没有。用的25，乱码。不能播放本地音乐。

**Comment by aegistar** [comment]
@sztsian
我尝试用了清华大学的镜像,解决了我的问题:https://mirrors4.tuna.tsinghua.edu.cn/help/fedora/

**Comment by sztsian** [comment]
@Oliverlyn 你的回复与本 ticket 无关。
中文用户组并不提供 Fedora 源。
本 ticket 是关于中文用户组源的，而 tuna 的帮助是关于 Fedora 官方源的。
