### ISSUE TITLE
fedora 26使用搜狗输入法的问题

### ISSUE THREAD

**Issue by chinaluopiao** [FZUG/repo#256]
我在fedora 26使用搜狗输入法，经常遇见用着用着 就fcitx 就变成僵尸进程了，然后就只能重启解决问题，请问下有什么解决方案吗

**Comment by shenwei356** [comment]
用 中州韻輸入法引擎 [fcitx-rime](https://github.com/fcitx/fcitx-rime)，爽得很，比搜狗稳定多了。

```
git clone https://github.com/fcitx/fcitx-rime
cd fcitx-rime
mkdir build; cd build
cmake ..
make -j 4
sudo make install
```
fcitx框架肯定要先安装。

**Comment by chinaluopiao** [comment]
刚刚安装了这个输入法，但是好像不能切换成简体中文，只能用繁体吗？

**Comment by cdadar** [comment]
可以切换的 `ctrl+~` 应该能 换了
![image](https://user-images.githubusercontent.com/8043088/28453151-91478aa4-6e28-11e7-8677-0d8efe1d4bd5.png)

**Comment by xixas** [comment]
https://copr.fedorainfracloud.org/coprs/mosquito/deepin/monitor/  why are some important packages not working? not able to install deeping in F26.... btw is this chinese only thread? or there is a englsih thread somewhere

**Comment by shenwei356** [comment]
@chinaluopiao @jiarenlu 配置文件可以设置用简体中文。没带电脑，你自己看一下。

**Comment by shenwei356** [comment]
@xixas please wait the maintainers for building packages for fc26.

**Comment by sztsian** [comment]
Hi @xixas you can use English here.
Since Sogou input method is not fully open source, we cannot help debug it. You are more than welcome if you have a clear step to reproduce your issue stably. 
I've talked with one of the community developers, he suggests if it blocks your daily work, currently the best solution is to use another input method like sunpinyin etc.
If you speak Chinese, you can read this thread https://github.com/FZUG/repo/issues/192
由于搜狗输入法不是完全开源的，所以我们没有办法调试。如果能提供稳定的复现步骤，将对此非常有利。
我与其中一位社区开发者讨论过，他说如果这个对你的日常工作已经有很大的影响，当前建议换其他的输入法。
中文用户可以阅读这个线索，也许对你有帮助 https://github.com/FZUG/repo/issues/192

**Comment by sztsian** [comment]
@xixas If you want to talk about deepin related packages, please file another issue. This thread is for Sogou input method.
And just FYI, we are now working on the deepin packages.

**Comment by sztsian** [comment]
Talked with the sogou input developer. As sogou input does not provide source code, the developer suggests all users who have problems using sogou to use other input methods.
