### ISSUE TITLE
Rebuild atom for F27+

### ISSUE THREAD

**Issue by poettler-ric** [FZUG/repo#283]
Hi,

could you please rebuild mosquito/atom for F27?

Kind regards
Richard Poettler

**Comment by cheese** [comment]
As a suggestion, installing atom from flathub is also a good idea.
https://flathub.org/apps.html

**Comment by poettler-ric** [comment]
Thanks for the suggestion, but I will not use  flatpack by any means.
I will then stick to the forked version of your port.

**Comment by 1dot75cm** [comment]
:) Atom **1.33.0** can be used on F28 F29 F30. @poettler-ric 

https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/834566/

**Comment by audreytoskin** [comment]
The Atom Flight Manual now [recommends](https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux) using the [repo from packagecloud](https://packagecloud.io/AtomEditor/atom/install#manual-rpm). There they only build RPMs of Atom for the latest RHEL release, but since the repo only contains Atom itself, it doesn't seem like it should cause any problems. You'll just need to update the repo URL string when they eventually switch from EL 7 to EL 8.

**Comment by audreytoskin** [comment]
...Oh, somehow I misunderstood the previous comment. A Copr is probably still the better solution -- the mosquito repo cleanly separates libraries and will automatically switch release versions when you upgrade Fedora, so I'm glad to see it being maintained again :+1:

**Comment by alick** [comment]
@1dot75cm Will you also put the atom RPMs in FZUG repo? (Or have you already) I think we can close this issue by then

**Comment by alick** [comment]
ping @1dot75cm

**Comment by 1dot75cm** [comment]
OK, I am planning. @alick

**Comment by alick** [comment]
considered done
