### ISSUE TITLE
deepin-picker for F27?

### ISSUE THREAD

**Issue by orschiro** [FZUG/repo#294]
Thanks for packaging the picker!

Can you provide a version that is compatible with F27?

Thanks. :-)

**Comment by sztsian** [comment]
Hi @orschiro ,
Thanks for reaching out. We are trying to get Deepin Desktop related packages into Fedora repo on Fedora 28 and later. We want to finish it by Fedora 29. Since the building environment differs a lot, it involves pretty much work. So currently we are not guaranteeing any work for Fedora 27, and we will postpone this to when we are available.

Thanks for understanding.

**Comment by orschiro** [comment]
@sztsian thanks! Great progress ahead I believe. :-)

So there is no way to currently run the picker on F27 right?

**Comment by sztsian** [comment]
Defer this question to @1dot75cm as I know little about the picker.

**Comment by 1dot75cm** [comment]
Please update your system to 29 (the mosquito/deepin Copr) or 30 (the official repository).

https://copr.fedorainfracloud.org/coprs/mosquito/deepin/build/831405/

https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Everything/x86_64/os/Packages/d/deepin-picker-1.6.4-1.fc30.x86_64.rpm

**Comment by sztsian** [comment]
> So there is no way to currently run the picker on F27 right?

Unfortunately, yes. Due to limited capacity, we won't support Deepin DE fully in Fedora 27.
